[build]
  command = "node netlify.build.js"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.x"
  NPM_FLAGS = "--legacy-peer-deps"

[dev]
  command = "npm run dev"
  port = 3000
  framework = "#static"

# Proxy API requests to the serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Proxy OAuth requests to the serverless function
[[redirects]]
  from = "/oauth/*"
  to = "/.netlify/functions/api/oauth/:splat"
  status = 200

# For all other routes, serve static files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  included_files = ["server/**", "shared/**"]
  external_node_modules = ["express"]